//! Canonical model-card JSON fixtures with pinned wire bytes.

pub(super) const CANONICAL_V2_CARD: &str = concat!(
    r#"{"schema":"maestro-model-card/2","identity":{"role":"embedder","router_entry":""#,
    r#"embed","weights":{"upstream_model_id":"org/model","upstream_revision":""#,
    r#"0123456789abcdef","source_url":"https://example.invalid/model","licence_id":""#,
    r#"apache-2.0","licence_terms_source":"https://example.invalid/license","gguf_"#,
    r#"digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","gguf"#,
    r#"_bytes":1024,"quantization":"Q8_0","adapters":{},"drafts":{},"projectors":{}},""#,
    r#"formats":{"tokenizer_digest":""#,
    r#"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","tokenizer_"#,
    r#"derivation":"gguf_embedded","qualification_digest":""#,
    r#"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","template":{""#,
    r#"state":"absent"},"system_format":"","tool_format":{"state":"unsupported"},""#,
    r#"document":{"state":"supported","value":{"prefix":"","suffix":""}},"query":{""#,
    r#"state":"supported","value":{"prefix":"Instruct: retrieve\\nQuery: ","suffix":""}"#,
    r#"},"embedding":{"state":"supported","value":{"pooling":"last_token",""#,
    r#"normalization":"l2"}}},"invocation":{"limits":{"context_tokens":4096,"output_"#,
    r#"tokens":null},"dimensions":{"state":"measured","value":1024},"sampling":{"state""#,
    r#":"not_applicable"},"reasoning":{"state":"not_applicable"},"llama_cpp_build":""#,
    r#"b1234-abcdef","runtime_binary_digest":""#,
    r#"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd","backend":""#,
    r#"cuda","server_flags":{"--model":{"type":"asset","value":{"name":"weights",""#,
    r#"digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}}}},""#,
    r#"resources":{"offload":{"mode":"explicit_devices","devices":["gpu0"]},"memory_"#,
    r#"estimate":{"bytes":2000000000,"source":"publisher estimate"},"slots":1,"kv_cache"#,
    r#"":{"key":"q8_0","value":"q8_0"},"cache_policy":"keep_loaded","batch_size":512,""#,
    r#"micro_batch_size":128,"hardware":{"device":"RTX 5090","driver_version":"616.56","#,
    r#""host_cpu":"test cpu","host_memory_bytes":{"state":"unavailable","reason":"not "#,
    r#"measured"}},"qualified_limits":{"context_tokens":{"state":"measured","value":"#,
    r#"4096,"provenance":"qualification run"},"output_tokens":{"state":"unavailable",""#,
    r#"reason":"not applicable"},"concurrency":{"state":"measured","value":1,""#,
    r#"provenance":"qualification run"},"peak_memory_bytes":{"state":"unavailable",""#,
    r#"reason":"not measured"}}},"provenance":{"identity_created":"2026-09-27",""#,
    r#"qualification_created":"2026-09-27","qualification_method":"native_tokenizer",""#,
    r#"tool_versions":{"llama.cpp":"b1234"},"artifacts":{"native-qualification":""#,
    r#"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"}}}}"#,
);

pub(super) const CANONICAL_ANSWERER_CARD: &str = concat!(
    r#"{"schema":"maestro-model-card/2","identity":{"role":"answerer","router_entry":""#,
    r#"embed","weights":{"upstream_model_id":"org/model","upstream_revision":""#,
    r#"0123456789abcdef","source_url":"https://example.invalid/model","licence_id":""#,
    r#"apache-2.0","licence_terms_source":"https://example.invalid/license","gguf_"#,
    r#"digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","gguf"#,
    r#"_bytes":1024,"quantization":"Q8_0","adapters":{},"drafts":{},"projectors":{}},""#,
    r#"formats":{"tokenizer_digest":""#,
    r#"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","tokenizer_"#,
    r#"derivation":"gguf_embedded","qualification_digest":""#,
    r#"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","template":{""#,
    r#"state":"absent"},"system_format":"","tool_format":{"state":"unsupported"},""#,
    r#"document":{"state":"not_applicable"},"query":{"state":"not_applicable"},""#,
    r#"embedding":{"state":"not_applicable"}},"invocation":{"limits":{"context_tokens":"#,
    r#"4096,"output_tokens":128},"dimensions":{"state":"not_applicable"},"sampling":{""#,
    r#"state":"configured","value":{"temperature":0.1,"top_p":0.9,"top_k":40,"min_p":0."#,
    r#"0,"typical_p":1.0,"repeat_penalty":1.0,"frequency_penalty":0.0,"presence_penalty"#,
    r#"":0.0,"seed":1}},"reasoning":{"state":"unsupported"},"llama_cpp_build":"b1234-"#,
    r#"abcdef","runtime_binary_digest":""#,
    r#"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd","backend":""#,
    r#"cuda","server_flags":{"--model":{"type":"asset","value":{"name":"weights",""#,
    r#"digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}},"--"#,
    r#"temperature":{"type":"number","value":0.1}}},"resources":{"offload":{"mode":""#,
    r#"explicit_devices","devices":["gpu0"]},"memory_estimate":{"bytes":2000000000,""#,
    r#"source":"publisher estimate"},"slots":1,"kv_cache":{"key":"q8_0","value":"q8_0"}"#,
    r#","cache_policy":"keep_loaded","batch_size":512,"micro_batch_size":128,"hardware""#,
    r#":{"device":"RTX 5090","driver_version":"616.56","host_cpu":"test cpu","host_"#,
    r#"memory_bytes":{"state":"unavailable","reason":"not measured"}},"qualified_limits"#,
    r#"":{"context_tokens":{"state":"measured","value":4096,"provenance":"qualification"#,
    r#" run"},"output_tokens":{"state":"unavailable","reason":"not applicable"},""#,
    r#"concurrency":{"state":"measured","value":1,"provenance":"qualification run"},""#,
    r#"peak_memory_bytes":{"state":"unavailable","reason":"not measured"}}},"provenance"#,
    r#"":{"identity_created":"2026-09-27","qualification_created":"2026-09-27",""#,
    r#"qualification_method":"native_tokenizer","tool_versions":{"llama.cpp":"b1234"},""#,
    r#"artifacts":{"native-qualification":""#,
    r#"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"}}}}"#,
);
