//! Read-only CODEOWNERS rendering to stdout and exact committed-file comparison.

use super::check::today;
use crate::{
    cli::output::Output,
    failure::Failure,
    presentation::{message::Message, messages::MessageKey},
};
use maestro_catalog::{
    limits::Limits,
    source::{CODEOWNERS_PATH, Directory, Known, Refusal, build, builtin, frozen_rows},
};
use serde::Serialize;
use std::{fs, io, path::Path, process::ExitCode};

/// The foreground authoring result; generated text is data under `--json`.
#[derive(Serialize)]
struct Document<'a> {
    /// Stable command document contract.
    schema: &'static str,
    /// `rendered` or `passed`.
    status: &'static str,
    /// Exact generated bytes as UTF-8, empty in check mode.
    codeowners: &'a str,
}

/// Preserve catalog-check's exit split for semantic versus I/O refusals.
fn failure(refusal: Refusal) -> Failure {
    if refusal.unreadable() {
        Failure::failed(refusal)
    } else {
        Failure::refused(refusal)
    }
}

/// Render without effects, or check the existing output without writing.
///
/// # Errors
/// Unsafe files, invalid source/area records, drift, missing output or stdout failure.
pub(in crate::cli) fn run(
    output: Output,
    catalog_dir: &Path,
    check: bool,
) -> Result<ExitCode, Failure> {
    // Check the final path without following it; the builder additionally holds
    // every ancestor and performs size-bounded, no-follow regular-file reads.
    match fs::symlink_metadata(catalog_dir.join(CODEOWNERS_PATH)) {
        Ok(metadata) if !metadata.is_file() => {
            return Err(Failure::refused_message(Message::new(
                MessageKey::CatalogCodeownersRegular,
                &[("path", CODEOWNERS_PATH)],
            )));
        }
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => {
            return Err(Failure::failed_message(Message::new(
                MessageKey::DiagnosticPath,
                &[("path", CODEOWNERS_PATH), ("error", &error.to_string())],
            )));
        }
    }
    let registry = builtin().map_err(Failure::failed)?;
    let rows = frozen_rows();
    let settings = maestro_settings::Registry::built_in().map_err(Failure::failed)?;
    let (catalog, generated) = build(
        &Directory::new(catalog_dir),
        &registry,
        &Limits::PRODUCTION,
        Known {
            rows: &rows,
            settings: &settings,
            today: today()?,
        },
    )
    .map_err(failure)?;
    let rendered = catalog.codeowners().map_err(Failure::refused)?;
    let text = if check {
        if generated.is_none() {
            let rule = rendered
                .lines()
                .find(|line| line.starts_with('/'))
                .unwrap_or("/*");
            return Err(Failure::refused_message(Message::new(
                MessageKey::CatalogCodeownersMissing,
                &[("path", CODEOWNERS_PATH), ("rule", rule)],
            )));
        }
        catalog
            .verify_generated(generated.as_deref())
            .map_err(failure)?;
        &output.wording(MessageKey::CatalogCodeownersPassed, &[])?
    } else {
        // Output::result adds exactly one newline; preserve the renderer's bytes.
        rendered.strip_suffix('\n').unwrap_or(&rendered)
    };
    output.result(
        &Document {
            schema: "maestro-cli/catalog-codeowners/1",
            status: if check { "passed" } else { "rendered" },
            codeowners: if check { "" } else { &rendered },
        },
        text,
    )?;
    Ok(ExitCode::SUCCESS)
}
