//! Read-only CODEOWNERS rendering to stdout and exact committed-file comparison.

use super::check::today;
use crate::{cli::output::Output, failure::Failure};
use maestro_catalog::{
    limits::Limits,
    source::{CODEOWNERS_PATH, Directory, Known, Refusal, build, builtin, frozen_rows},
};
use serde::Serialize;
use std::{fs, io, path::Path, process::ExitCode};

/// The foreground authoring result; generated text is data under `--json`.
#[derive(Serialize)]
struct Document<'a> {
    /// Stable command document contract.
    schema: &'static str,
    /// `rendered` or `passed`.
    status: &'static str,
    /// Exact generated bytes as UTF-8, empty in check mode.
    codeowners: &'a str,
}

/// Preserve catalog-check's exit split for semantic versus I/O refusals.
fn failure(refusal: Refusal) -> Failure {
    if refusal.unreadable() {
        Failure::failed(refusal)
    } else {
        Failure::refused(refusal)
    }
}

/// Render without effects, or check the existing output without writing.
///
/// # Errors
/// Unsafe files, invalid source/area records, drift, missing output or stdout failure.
pub(in crate::cli) fn run(
    output: Output,
    catalog_dir: &Path,
    check: bool,
) -> Result<ExitCode, Failure> {
    // Check the final path without following it; the builder additionally holds
    // every ancestor and performs size-bounded, no-follow regular-file reads.
    match fs::symlink_metadata(catalog_dir.join(CODEOWNERS_PATH)) {
        Ok(metadata) if !metadata.is_file() => {
            return Err(Failure::refused(format!(
                "{CODEOWNERS_PATH}: generated CODEOWNERS must be a regular file"
            )));
        }
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(Failure::failed(format!("{CODEOWNERS_PATH}: {error}"))),
    }
    let registry = builtin().map_err(Failure::failed)?;
    let rows = frozen_rows();
    let settings = maestro_settings::Registry::built_in().map_err(Failure::failed)?;
    let (catalog, generated) = build(
        &Directory::new(catalog_dir),
        &registry,
        &Limits::PRODUCTION,
        Known {
            rows: &rows,
            settings: &settings,
            today: today()?,
        },
    )
    .map_err(failure)?;
    let rendered = catalog.codeowners().map_err(Failure::refused)?;
    let text = if check {
        if generated.is_none() {
            let rule = rendered
                .lines()
                .find(|line| line.starts_with('/'))
                .unwrap_or("/*");
            return Err(Failure::refused(format!(
                "{CODEOWNERS_PATH}: missing file; expected rule {rule}"
            )));
        }
        catalog
            .verify_generated(generated.as_deref())
            .map_err(failure)?;
        "CODEOWNERS check passed"
    } else {
        // Output::result adds exactly one newline; preserve the renderer's bytes.
        rendered.strip_suffix('\n').unwrap_or(&rendered)
    };
    output.result(
        &Document {
            schema: "maestro-cli/catalog-codeowners/1",
            status: if check { "passed" } else { "rendered" },
            codeowners: if check { "" } else { &rendered },
        },
        text,
    )?;
    Ok(ExitCode::SUCCESS)
}

#[cfg(test)]
mod tests {
    use super::run;
    use crate::{cli::output::Output, failure::Failure};
    use maestro_test_scratch::scratch_directory;
    use std::fs;

    #[test]
    fn codeowners_directory_refusal_names_the_regular_file_requirement() {
        let scratch = scratch_directory().unwrap();
        fs::create_dir_all(scratch.join(".github/CODEOWNERS")).unwrap();
        let error = run(Output::new(false), &scratch, true).unwrap_err();
        let expected = ".github/CODEOWNERS: generated CODEOWNERS must be a regular file";
        let refused = matches!(error, Failure::Refused(ref message) if message == expected);
        assert!(refused, "{error}");
        fs::remove_dir_all(scratch).unwrap();
    }

    // A path under a regular file is ENOTDIR on Unix (a non-NotFound metadata
    // error); Windows reports NotFound, which this code correctly treats as absent.
    #[cfg(unix)]
    #[test]
    fn codeowners_metadata_errors_preserve_the_failed_path() {
        let scratch = scratch_directory().unwrap();
        fs::write(scratch.join(".github"), "not a directory").unwrap();
        let error = run(Output::new(false), &scratch, true).unwrap_err();
        let failed = matches!(error,
            Failure::Failed(ref message) if message.starts_with(".github/CODEOWNERS:"));
        assert!(failed, "{error}");
        fs::remove_dir_all(scratch).unwrap();
    }
}
