//! Frozen project defaults admitted through checked trust and C04 committed ownership.
use super::{defaults::manifest_registry, discovery::SessionPreferences};
use crate::{
    files::{FileInput, FilePlan, digest},
    limits::Limits,
    policy::workspace::{Access, CheckedTrust, WorkspaceTrust as _},
};
use maestro_settings::Registry;
use serde::Deserialize;
use std::{
    collections::BTreeSet,
    io::{self, Read as _},
    path::Path,
};

/// The bounded defaults/outputs envelope; source identities are authoring data only.
#[derive(Deserialize)]
struct Lock {
    /// Exact schema, never installation/trust authority.
    schema: String,
    /// Captured lowest defaults slot, never user overrides.
    defaults: String,
    /// Runtime base types checked at init against linked adapters.
    backend_types: BTreeSet<String>,
    /// Original generated outputs needed to reconstruct C04's immutable plan.
    files: Vec<LockedFile>,
}

/// One generated file pinned by init.
#[derive(Deserialize)]
struct LockedFile {
    /// Normalized root-relative output path, checked by C04.
    path: String,
    /// Digest of the original generated bytes.
    sha256: String,
}

impl SessionPreferences {
    /// Admit a captured project lock only under a journal-approved containing root.
    /// No lock preserves legacy defaults. Existing locks cannot fall back on refusal.
    /// The lock and generated output digests must exactly replay a committed C04 plan.
    /// Catalog edits are never reread; the snapshot survives subsequent lock edits.
    ///
    /// # Errors
    /// Refuses untrusted, changed, malformed, oversized or uncommitted locks/outputs,
    /// or base adapters missing from the composition root's compiled set.
    pub fn admit_defaults(
        mut self,
        trust: &CheckedTrust<'_>,
        compiled: &BTreeSet<String>,
        limits: &Limits,
    ) -> Result<Self, String> {
        let Some(path) = self.lock.take().transpose()? else {
            return Ok(self);
        };
        let root = path
            .parent()
            .and_then(Path::parent)
            .ok_or("invalid lock placement")?;
        if trust.containing_root(root).is_none() {
            return Err("project defaults require a trusted containing root".to_owned());
        }
        let bytes = trust
            .authorize(
                root,
                Path::new(".maestro/authoring.lock.json"),
                Access::Read,
            )
            .and_then(|path| path.read_preferences(limits.source_file_bytes))
            .map_err(|error| format!("project lock cannot be read; run preview again: {error}"))?;
        let lock: Lock = serde_json::from_slice(&bytes)
            .map_err(|_| "invalid project lock; run preview again")?;
        if lock.schema != "maestro-authoring-lock/2" {
            return Err("unsupported project lock; run preview again".to_owned());
        }
        let mut files = Vec::new();
        let mut total = u64::try_from(bytes.len()).map_err(|error| error.to_string())?;
        if lock.files.len() >= limits.archive_entries {
            return Err("project lock output count exceeds limit".to_owned());
        }
        for entry in lock.files {
            let bytes = read(root, &entry.path, trust, limits.source_file_bytes)
                .map_err(|error| error.to_string())?;
            total += u64::try_from(bytes.len()).map_err(|error| error.to_string())?;
            if total > limits.archive_total_bytes {
                return Err("project lock output bytes exceed limit".to_owned());
            }
            if digest(&bytes) != entry.sha256 {
                return Err("project lock output changed; run preview again".to_owned());
            }
            files.push(FileInput::new(entry.path, bytes));
        }
        files.push(FileInput::new(".maestro/authoring.lock.json", bytes));
        committed_plan(root, files, trust)?;
        if lock
            .backend_types
            .iter()
            .any(|kind| kind != "none" && !compiled.contains(kind))
        {
            return Err("backend adapter is not compiled into this build".to_owned());
        }
        self.registry = manifest_registry(
            &Registry::built_in().map_err(|error| error.to_string())?,
            &[(".maestro/authoring.lock.json".to_owned(), lock.defaults)],
            limits,
        )
        .map_err(|(path, key, message)| format!("{path}: {key}: {message}"))?;
        Ok(self)
    }
}

/// Reconstruct committed C04 ownership, including a lock captured before deletion.
fn committed_plan(
    root: &Path,
    files: Vec<FileInput>,
    trust: &CheckedTrust<'_>,
) -> Result<(), String> {
    let plan = FilePlan::preview(root, files, trust)
        .map_err(|error| format!("project lock changed; run preview again: {error}"))?;
    if !plan.is_applied() {
        return Err("project lock has no committed ownership; run preview again".to_owned());
    }
    Ok(())
}

/// Held-handle, checked non-secret reads with the same source-file byte ceiling.
fn read(root: &Path, relative: &str, trust: &CheckedTrust<'_>, max: u64) -> io::Result<Vec<u8>> {
    let file = trust
        .authorize(root, Path::new(relative), Access::Read)?
        .open_read()?;
    let mut bytes = Vec::new();
    file.take(max.saturating_add(1)).read_to_end(&mut bytes)?;
    if u64::try_from(bytes.len()).unwrap_or(u64::MAX) > max {
        return Err(io::Error::other("project output exceeds byte limit"));
    }
    Ok(bytes)
}

#[cfg(test)]
mod tests {
    use super::committed_plan;
    use crate::files::{FileInput, tests::support::with_trust};
    use maestro_test_scratch::scratch_directory;
    use std::fs;

    #[test]
    fn captured_uncommitted_lock_cannot_be_republished() {
        let root = scratch_directory().unwrap();
        with_trust(&root, |trust| {
            let captured = vec![FileInput::new(
                ".maestro/authoring.lock.json",
                b"captured lock".to_vec(),
            )];
            let error = committed_plan(&root, captured, trust).unwrap_err();
            assert!(error.contains("no committed ownership"), "{error}");
        });
        assert_eq!(fs::read_dir(&root).unwrap().count(), 0);
        fs::remove_dir_all(root).unwrap();
    }
}
