//! Deterministic public-source navigation; no release or installation authority.

use super::{
    Diagnostic, Known, Refusal, Registry, SourceTree,
    check::checked_snapshot,
    ownership::{BY_TYPE_PATH, INDEX_PATH},
};
use crate::{files::digest, limits::Limits};
use maestro_kernel::json::canonical;
use serde::Serialize;
use std::{collections::BTreeMap, io};

/// The two generated navigation views, always UTF-8 with LF line endings.
#[derive(Debug)]
pub struct CatalogIndex {
    /// The versioned JSON index.
    pub index: String,
    /// The Markdown navigation by registered kind.
    pub by_type: String,
    /// Existing index bytes from the same checked snapshot, never reread.
    committed_index: Option<Vec<u8>>,
    /// Existing type-view bytes from the same checked snapshot, never reread.
    committed_by_type: Option<Vec<u8>>,
}

/// A checked resource and its exact source pins; not a release identity.
#[derive(Serialize)]
struct Row {
    /// Qualified source identity.
    id: String,
    /// Registered type used to group navigation.
    kind: String,
    /// Primary catalog-relative source path.
    path: String,
    /// Exact declared version, absent for unversioned sources.
    version: Option<String>,
    /// Checked declared evidence stage, never runtime qualification.
    maturity: &'static str,
    /// Exact source, sidecar and inventoried inert asset pins in path order.
    sources: BTreeMap<String, String>,
}

impl CatalogIndex {
    /// Compare both generated views against retained snapshot bytes.
    ///
    /// # Errors
    /// Missing, stale, extra or private rows refuse; no private input is echoed.
    pub fn verify(&self, index: Option<&[u8]>, by_type: Option<&[u8]>) -> Result<(), Refusal> {
        let mut diagnostics = Vec::new();
        for (path, expected, actual, view) in [
            (INDEX_PATH, self.index.as_bytes(), index, "index"),
            (BY_TYPE_PATH, self.by_type.as_bytes(), by_type, "by-type"),
        ] {
            if actual == Some(expected) {
                continue;
            }
            let problem = if actual.is_none() {
                "missing"
            } else {
                "stale, extra or private rows"
            };
            diagnostics.push(Diagnostic::new(
                path,
                "",
                format!(
                    "{problem}; from the public catalog directory run: \
                 mkdir -p marketplace docs/catalog; \
                 maestro catalog index --catalog-dir . --view {view} > {path}"
                ),
            ));
        }
        if diagnostics.is_empty() {
            Ok(())
        } else {
            Err(Refusal { diagnostics })
        }
    }

    /// Compare both committed views without reopening any source/output.
    ///
    /// # Errors
    /// Missing or differing generated bytes refuse.
    pub fn verify_committed(&self) -> Result<(), Refusal> {
        self.verify(
            self.committed_index.as_deref(),
            self.committed_by_type.as_deref(),
        )
    }
}

/// Generate navigation from the public pinned source alone. The caller supplies
/// the public source slot, never a private overlay, workspace or user source.
/// Each digest covers the exact checked bytes, including original line endings;
/// the two rendered views themselves use LF on every host. No content is executed.
///
/// # Errors
/// Source checking refuses invalid, unsafe or oversized public inputs.
pub fn generate(
    public: &dyn SourceTree,
    registry: &Registry,
    limits: &Limits,
    known: Known<'_>,
) -> Result<CatalogIndex, Refusal> {
    let (catalog, snapshot) = checked_snapshot(public, registry, limits, known)?;
    let mut rows = Vec::new();
    let mut groups = BTreeMap::<&str, Vec<String>>::new();
    for resource in &catalog.resources {
        let mut sources = BTreeMap::new();
        let defaults = catalog
            .common_defaults
            .as_ref()
            .filter(|_| resource.id.kind == "package" && resource.id.name == "common")
            .map(|_| super::defaults::DEFAULTS_PATH);
        for path in resource
            .files
            .iter()
            .chain(&resource.data)
            .map(String::as_str)
            .chain(defaults)
        {
            let bytes = snapshot
                .read(path, limits.source_file_bytes)
                .map_err(|error| Refusal {
                    diagnostics: vec![Diagnostic::unreadable(path, error.to_string())],
                })?;
            sources.insert(path.to_owned(), digest(&bytes));
        }
        let id = resource.id.to_string();
        groups
            .entry(&resource.id.kind)
            .or_default()
            .push(format!("- `{id}` — `{}`\n", resource.path));
        rows.push(Row {
            id,
            kind: resource.id.kind.clone(),
            path: resource.path.clone(),
            version: resource.source_revision(),
            maturity: resource.metadata.maturity.as_str(),
            sources,
        });
    }
    let document = serde_json::json!({ "schema": "maestro-catalog/index/1", "resources": rows });
    let index = format!("{}\n", canonical(document));
    let mut by_type = "# Catalog by type\n\n\
        Generated from public pinned sources; navigation is not release authority.\n"
        .to_owned();
    for (kind, entries) in groups {
        by_type.push_str("\n## ");
        by_type.push_str(kind);
        by_type.push_str("\n\n");
        by_type.extend(entries);
    }
    Ok(CatalogIndex {
        index,
        by_type,
        committed_index: retained(&snapshot, INDEX_PATH, limits)?,
        committed_by_type: retained(&snapshot, BY_TYPE_PATH, limits)?,
    })
}

/// Optional bytes from the bounded snapshot, with the standard I/O exit split.
fn retained(
    snapshot: &dyn SourceTree,
    path: &str,
    limits: &Limits,
) -> Result<Option<Vec<u8>>, Refusal> {
    match snapshot.read(path, limits.source_file_bytes) {
        Ok(bytes) => Ok(Some(bytes)),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(Refusal {
            diagnostics: vec![Diagnostic::unreadable(path, error.to_string())],
        }),
    }
}
